---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2025 The Linux Foundation

# Action test/validation workflow
name: "Test GitHub Action 🧪"

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

permissions: {}

jobs:
  ### Test the GitHub Action in this Repository ###
  tests:
    name: "Test local GitHub Action"
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    timeout-minutes: 8
    steps:
      - name: "Running local action: ${{ github.repository }} 25.02.3"
        uses: $/
        id: short-year
        with:
          string: "25.02.3"

      - name: "Error if short-year tag not valid"
        if: steps.short-year.outputs.valid != 'true'
        shell: bash
        run: |
          # Error if short-year tag not valid
          echo "Error: short-year tag was not flagged valid ❌"
          exit 1

      - name: "Running local action: ${{ github.repository }} 24.04"
        uses: $/
        id: short-year-two-segment
        with:
          string: "24.04"

      - name: "Error if two-segment short-year tag not valid"
        if: steps.short-year-two-segment.outputs.valid != 'true'
        shell: bash
        run: |
          # Error if two-segment short-year tag not valid
          echo "Error: two-segment short-year tag was not flagged valid ❌"
          exit 1

      - name: "Running local action: ${{ github.repository }} 2025.02.3"
        uses: $/
        id: long-year
        with:
          string: "2025.02.3"

      - name: "Error if long-year tag not valid"
        if: steps.long-year.outputs.valid != 'true'
        shell: bash
        run: |
          # Error if long-year tag not valid
          echo "Error: long-year tag was not flagged valid ❌"
          exit 1

      - name: "Running local action: ${{ github.repository }} 2025.02"
        uses: $/
        id: long-year-two-segment
        with:
          string: "2025.02"

      - name: "Error if two-segment long-year tag not valid"
        if: steps.long-year-two-segment.outputs.valid != 'true'
        shell: bash
        run: |
          # Error if two-segment long-year tag not valid
          echo "Error: two-segment long-year tag was not flagged valid ❌"
          exit 1

      - name: "Running local action: ${{ github.repository }} v2025.02.3-dev1"
        uses: $/
        id: dev-tag
        with:
          string: "v2025.02.3-dev1"

      - name: "Error if development tag not valid"
        if: steps.dev-tag.outputs.valid != 'true'
        shell: bash
        run: |
          # Error if development tag not valid
          echo "Error: development tag was not flagged valid ❌"
          exit 1

      - name: "Error if development tag not flagged"
        if: steps.dev-tag.outputs.dev_version != 'true'
        shell: bash
        run: |
          # Error if development tag not flagged
          echo "Error: development tag was not flagged ❌"
          exit 1

      # yamllint disable-line rule:line-length
      - name: "Running local action: ${{ github.repository }} v1.not-valid.3.garbage [NOT CalVer]"
        uses: $/
        id: not-calver
        with:
          string: "v1.not-valid.3.garbage"

      - name: "Error if non-CalVer string not rejected"
        if: steps.not-calver.outputs.valid != 'false'
        shell: bash
        run: |
          # Error if non-CalVer string not rejected
          echo "Error: non-CalVer string was flagged valid ❌"
          exit 1

      # yamllint disable-line rule:line-length
      - name: "Running local action: ${{ github.repository }} 2025x02.3.0 [NOT CalVer]"
        uses: $/
        id: bad-separator
        with:
          string: "2025x02.3.0"

      - name: "Error if bad year separator not rejected"
        if: steps.bad-separator.outputs.valid != 'false'
        shell: bash
        run: |
          # Error if bad year separator not rejected
          echo "Error: bad year separator was flagged valid ❌"
          exit 1

      # yamllint disable-line rule:line-length
      - name: "Running local action: ${{ github.repository }} 99a1.1.x [NOT CalVer]"
        uses: $/
        id: bad-separator-short-year
        with:
          string: "99a1.1.x"

      - name: "Error if bad short-year separator not rejected"
        if: steps.bad-separator-short-year.outputs.valid != 'false'
        shell: bash
        run: |
          # Error if bad short-year separator not rejected
          echo "Error: bad short-year separator was flagged valid ❌"
          exit 1

      # yamllint disable-line rule:line-length
      - name: "Running local action: ${{ github.repository }} [Override Failure]"
        uses: $/
        id: failure
        continue-on-error: true
        with:
          string: "v1.not-valid.3.garbage"
          exit_on_fail: true

      - name: "Error if step above did NOT fail"
        if: steps.failure.outcome == 'success'
        shell: bash
        run: |
          # Error if step above did NOT fail
          echo "Error: previous test step did NOT fail ❌"
          exit 1
