---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2025 The Linux Foundation

# Action test/validation workflow
name: "Test GitHub Action 🧪"

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions: {}

jobs:
  ### Test the GitHub Action in this Repository ###
  tests:
    name: "Test local GitHub Action"
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: "Running local action: ${{ github.repository }} 25.02.3"
        uses: ./
        with:
          string: "25.02.3"

      - name: "Running local action: ${{ github.repository }} 2025.02.3"
        uses: ./
        with:
          string: "2025.02.3"

      - name: "Running local action: ${{ github.repository }} v2025.02.3-dev1"
        uses: ./
        id: dev-tag
        with:
          string: "v2025.02.3-dev1"

      - name: "Error if development tag not flagged"
        if: steps.dev-tag.outputs.dev_version != 'true'
        shell: bash
        run: |
          # Error if development tag not flagged
          echo "Error: development tag was not flagged ❌"
          exit 1

      # yamllint disable-line rule:line-length
      - name: "Running local action: ${{ github.repository }} v1.not-valid.3.garbage [NOT CalVer]"
        uses: ./
        with:
          string: "v1.not-valid.3.garbage"

      # yamllint disable-line rule:line-length
      - name: "Running local action: ${{ github.repository }} [Override Failure]"
        uses: ./
        id: failure
        continue-on-error: true
        with:
          string: "v1.not-valid.3.garbage"
          exit_on_fail: true

      - name: "Error if step above did NOT fail"
        if: steps.failure.outcome == 'success'
        shell: bash
        run: |
          # Error if step above did NOT fail
          echo "Error: previous test step did NOT fail ❌"
          exit 1
